{"uuid": "5e94a3ec-6eed-4f3c-8959-6bd55c832324", "children": ["862e7cb7-22ae-4931-9919-2b1e3022f7b2"], "befores": [{"name": "loginapp", "status": "broken", "statusDetails": {"message": "TypeError: exceptions must derive from BaseException\n", "trace": "  File \"D:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\admin\\Desktop\\zidonghua\\AppTestCase\\conftest.py\", line 10, in loginapp\n  File \"D:\\vip\\V207\\UI自动化测试框架四app自动化\\zidonghua\\untils\\initAPP.py\", line 52, in click_my\n    ele=self.until_element_visible(loc)\n  File \"D:\\vip\\V207\\UI自动化测试框架四app自动化\\zidonghua\\untils\\initAPP.py\", line 42, in until_element_visible\n    raise (\"等待了5miao没有找到该元素\")\n"}, "attachments": [{"name": "app错误截图", "source": "a4b7730c-867a-4d8a-a563-c062ad04f98b-attachment.jpg", "type": "image/jpg"}], "start": 1604405804373, "stop": 1604405810248}], "start": 1604405804373, "stop": 1604405810333}